# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\"2\n\x0b\x41uthRequest\x12\x11\n\tauth_code\x18\x01 \x01(\t\x12\x10\n\x08platform\x18\x02 \x01(\x05\"3\n\x0c\x41uthResponse\x12\x11\n\tauth_code\x18\x01 \x01(\t\x12\x10\n\x08playerId\x18\x02 \x01(\x03\x32\x34\n\x04\x61uth\x12,\n\x0bviaAuthCode\x12\x0c.AuthRequest\x1a\r.AuthResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUTHREQUEST']._serialized_start=14
  _globals['_AUTHREQUEST']._serialized_end=64
  _globals['_AUTHRESPONSE']._serialized_start=66
  _globals['_AUTHRESPONSE']._serialized_end=117
  _globals['_AUTH']._serialized_start=119
  _globals['_AUTH']._serialized_end=171
# @@protoc_insertion_point(module_scope)
