# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\"F\n\x15GetInventoriesRequest\x12\x1c\n\x07players\x18\x01 \x03(\x0b\x32\x0b.PlayerInfo\x12\x0f\n\x07invType\x18\x02 \x01(\x05\"\x1f\n\nPlayerInfo\x12\x11\n\tpersonaId\x18\x01 \x01(\x03\"\x18\n\x16GetInventoriesResponse2P\n\tinventory\x12\x43\n\x0egetInventories\x12\x16.GetInventoriesRequest\x1a\x17.GetInventoriesResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETINVENTORIESREQUEST']._serialized_start=19
  _globals['_GETINVENTORIESREQUEST']._serialized_end=89
  _globals['_PLAYERINFO']._serialized_start=91
  _globals['_PLAYERINFO']._serialized_end=122
  _globals['_GETINVENTORIESRESPONSE']._serialized_start=124
  _globals['_GETINVENTORIESRESPONSE']._serialized_end=148
  _globals['_INVENTORY']._serialized_start=150
  _globals['_INVENTORY']._serialized_end=230
# @@protoc_insertion_point(module_scope)
