# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import PrivateGames_pb2 as PrivateGames__pb2


class PrivateGamesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getPlayground = channel.unary_unary(
                '/PrivateGames/getPlayground',
                request_serializer=PrivateGames__pb2.PlaygroundRequest.SerializeToString,
                response_deserializer=PrivateGames__pb2.PlaygroundResponse.FromString,
                )
        self.GetConstraints = channel.unary_unary(
                '/PrivateGames/GetConstraints',
                request_serializer=PrivateGames__pb2.Empty.SerializeToString,
                response_deserializer=PrivateGames__pb2.GetConstraintsResponse.FromString,
                )
        self.listPlaygroundsByOwner = channel.unary_unary(
                '/PrivateGames/listPlaygroundsByOwner',
                request_serializer=PrivateGames__pb2.ListPlaygroundsByOwnerRequest.SerializeToString,
                response_deserializer=PrivateGames__pb2.ListPlaygroundsByOwnerResponse.FromString,
                )
        self.getScheduledBlueprints = channel.unary_unary(
                '/PrivateGames/getScheduledBlueprints',
                request_serializer=PrivateGames__pb2.GetScheduledBlueprintsRequest.SerializeToString,
                response_deserializer=PrivateGames__pb2.GetScheduledBlueprintsResponse.FromString,
                )
        self.getBlueprintsById = channel.unary_unary(
                '/PrivateGames/getBlueprintsById',
                request_serializer=PrivateGames__pb2.GetBlueprintsByIdRequest.SerializeToString,
                response_deserializer=PrivateGames__pb2.GetBlueprintsByIdResponse.FromString,
                )
        self.createGameTemplate = channel.unary_unary(
                '/PrivateGames/createGameTemplate',
                request_serializer=PrivateGames__pb2.CreateGameTemplateRequest.SerializeToString,
                response_deserializer=PrivateGames__pb2.CreateGameTemplateResponse.FromString,
                )


class PrivateGamesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getPlayground(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConstraints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listPlaygroundsByOwner(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getScheduledBlueprints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getBlueprintsById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createGameTemplate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PrivateGamesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getPlayground': grpc.unary_unary_rpc_method_handler(
                    servicer.getPlayground,
                    request_deserializer=PrivateGames__pb2.PlaygroundRequest.FromString,
                    response_serializer=PrivateGames__pb2.PlaygroundResponse.SerializeToString,
            ),
            'GetConstraints': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConstraints,
                    request_deserializer=PrivateGames__pb2.Empty.FromString,
                    response_serializer=PrivateGames__pb2.GetConstraintsResponse.SerializeToString,
            ),
            'listPlaygroundsByOwner': grpc.unary_unary_rpc_method_handler(
                    servicer.listPlaygroundsByOwner,
                    request_deserializer=PrivateGames__pb2.ListPlaygroundsByOwnerRequest.FromString,
                    response_serializer=PrivateGames__pb2.ListPlaygroundsByOwnerResponse.SerializeToString,
            ),
            'getScheduledBlueprints': grpc.unary_unary_rpc_method_handler(
                    servicer.getScheduledBlueprints,
                    request_deserializer=PrivateGames__pb2.GetScheduledBlueprintsRequest.FromString,
                    response_serializer=PrivateGames__pb2.GetScheduledBlueprintsResponse.SerializeToString,
            ),
            'getBlueprintsById': grpc.unary_unary_rpc_method_handler(
                    servicer.getBlueprintsById,
                    request_deserializer=PrivateGames__pb2.GetBlueprintsByIdRequest.FromString,
                    response_serializer=PrivateGames__pb2.GetBlueprintsByIdResponse.SerializeToString,
            ),
            'createGameTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.createGameTemplate,
                    request_deserializer=PrivateGames__pb2.CreateGameTemplateRequest.FromString,
                    response_serializer=PrivateGames__pb2.CreateGameTemplateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PrivateGames', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PrivateGames(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getPlayground(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PrivateGames/getPlayground',
            PrivateGames__pb2.PlaygroundRequest.SerializeToString,
            PrivateGames__pb2.PlaygroundResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetConstraints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PrivateGames/GetConstraints',
            PrivateGames__pb2.Empty.SerializeToString,
            PrivateGames__pb2.GetConstraintsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def listPlaygroundsByOwner(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PrivateGames/listPlaygroundsByOwner',
            PrivateGames__pb2.ListPlaygroundsByOwnerRequest.SerializeToString,
            PrivateGames__pb2.ListPlaygroundsByOwnerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getScheduledBlueprints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PrivateGames/getScheduledBlueprints',
            PrivateGames__pb2.GetScheduledBlueprintsRequest.SerializeToString,
            PrivateGames__pb2.GetScheduledBlueprintsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getBlueprintsById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PrivateGames/getBlueprintsById',
            PrivateGames__pb2.GetBlueprintsByIdRequest.SerializeToString,
            PrivateGames__pb2.GetBlueprintsByIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def createGameTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PrivateGames/createGameTemplate',
            PrivateGames__pb2.CreateGameTemplateRequest.SerializeToString,
            PrivateGames__pb2.CreateGameTemplateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
