# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import PrivateGames_pb2 as PrivateGames__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in PrivateGames_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PrivateGamesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getPlayground = channel.unary_unary(
                '/PrivateGames/getPlayground',
                request_serializer=PrivateGames__pb2.PlaygroundRequest.SerializeToString,
                response_deserializer=PrivateGames__pb2.PlaygroundResponse.FromString,
                _registered_method=True)
        self.GetConstraints = channel.unary_unary(
                '/PrivateGames/GetConstraints',
                request_serializer=PrivateGames__pb2.Empty.SerializeToString,
                response_deserializer=PrivateGames__pb2.GetConstraintsResponse.FromString,
                _registered_method=True)
        self.listPlaygroundsByOwner = channel.unary_unary(
                '/PrivateGames/listPlaygroundsByOwner',
                request_serializer=PrivateGames__pb2.ListPlaygroundsByOwnerRequest.SerializeToString,
                response_deserializer=PrivateGames__pb2.ListPlaygroundsByOwnerResponse.FromString,
                _registered_method=True)
        self.getScheduledBlueprints = channel.unary_unary(
                '/PrivateGames/getScheduledBlueprints',
                request_serializer=PrivateGames__pb2.GetScheduledBlueprintsRequest.SerializeToString,
                response_deserializer=PrivateGames__pb2.GetScheduledBlueprintsResponse.FromString,
                _registered_method=True)
        self.getBlueprintsById = channel.unary_unary(
                '/PrivateGames/getBlueprintsById',
                request_serializer=PrivateGames__pb2.GetBlueprintsByIdRequest.SerializeToString,
                response_deserializer=PrivateGames__pb2.GetBlueprintsByIdResponse.FromString,
                _registered_method=True)
        self.createGameTemplate = channel.unary_unary(
                '/PrivateGames/createGameTemplate',
                request_serializer=PrivateGames__pb2.CreateGameTemplateRequest.SerializeToString,
                response_deserializer=PrivateGames__pb2.CreateGameTemplateResponse.FromString,
                _registered_method=True)


class PrivateGamesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getPlayground(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConstraints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listPlaygroundsByOwner(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getScheduledBlueprints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getBlueprintsById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createGameTemplate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PrivateGamesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getPlayground': grpc.unary_unary_rpc_method_handler(
                    servicer.getPlayground,
                    request_deserializer=PrivateGames__pb2.PlaygroundRequest.FromString,
                    response_serializer=PrivateGames__pb2.PlaygroundResponse.SerializeToString,
            ),
            'GetConstraints': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConstraints,
                    request_deserializer=PrivateGames__pb2.Empty.FromString,
                    response_serializer=PrivateGames__pb2.GetConstraintsResponse.SerializeToString,
            ),
            'listPlaygroundsByOwner': grpc.unary_unary_rpc_method_handler(
                    servicer.listPlaygroundsByOwner,
                    request_deserializer=PrivateGames__pb2.ListPlaygroundsByOwnerRequest.FromString,
                    response_serializer=PrivateGames__pb2.ListPlaygroundsByOwnerResponse.SerializeToString,
            ),
            'getScheduledBlueprints': grpc.unary_unary_rpc_method_handler(
                    servicer.getScheduledBlueprints,
                    request_deserializer=PrivateGames__pb2.GetScheduledBlueprintsRequest.FromString,
                    response_serializer=PrivateGames__pb2.GetScheduledBlueprintsResponse.SerializeToString,
            ),
            'getBlueprintsById': grpc.unary_unary_rpc_method_handler(
                    servicer.getBlueprintsById,
                    request_deserializer=PrivateGames__pb2.GetBlueprintsByIdRequest.FromString,
                    response_serializer=PrivateGames__pb2.GetBlueprintsByIdResponse.SerializeToString,
            ),
            'createGameTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.createGameTemplate,
                    request_deserializer=PrivateGames__pb2.CreateGameTemplateRequest.FromString,
                    response_serializer=PrivateGames__pb2.CreateGameTemplateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PrivateGames', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('PrivateGames', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PrivateGames(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getPlayground(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PrivateGames/getPlayground',
            PrivateGames__pb2.PlaygroundRequest.SerializeToString,
            PrivateGames__pb2.PlaygroundResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConstraints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PrivateGames/GetConstraints',
            PrivateGames__pb2.Empty.SerializeToString,
            PrivateGames__pb2.GetConstraintsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def listPlaygroundsByOwner(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PrivateGames/listPlaygroundsByOwner',
            PrivateGames__pb2.ListPlaygroundsByOwnerRequest.SerializeToString,
            PrivateGames__pb2.ListPlaygroundsByOwnerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getScheduledBlueprints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PrivateGames/getScheduledBlueprints',
            PrivateGames__pb2.GetScheduledBlueprintsRequest.SerializeToString,
            PrivateGames__pb2.GetScheduledBlueprintsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getBlueprintsById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PrivateGames/getBlueprintsById',
            PrivateGames__pb2.GetBlueprintsByIdRequest.SerializeToString,
            PrivateGames__pb2.GetBlueprintsByIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def createGameTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PrivateGames/createGameTemplate',
            PrivateGames__pb2.CreateGameTemplateRequest.SerializeToString,
            PrivateGames__pb2.CreateGameTemplateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
