# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stats.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'stats.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstats.proto\"\"\n\x0fGetStatsRequest\x12\x0f\n\x07players\x18\x02 \x03(\x03\"(\n\tStatField\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\"\'\n\tCatFields\x12\x1a\n\x06\x66ields\x18\x01 \x03(\x0b\x32\n.StatField\">\n\x0cStatCategory\x12\x0f\n\x07\x63\x61tName\x18\x01 \x01(\t\x12\x1d\n\tcatFields\x18\x02 \x01(\x0b\x32\n.CatFields\"?\n\nPlayerStat\x12\x0e\n\x06player\x18\x01 \x01(\x03\x12!\n\ncategories\x18\x02 \x03(\x0b\x32\r.StatCategory\"4\n\x10GetStatsResponse\x12 \n\x0bplayerStats\x18\x01 \x03(\x0b\x32\x0b.PlayerStat2:\n\x05stats\x12\x31\n\x08getStats\x12\x10.GetStatsRequest\x1a\x11.GetStatsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stats_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETSTATSREQUEST']._serialized_start=15
  _globals['_GETSTATSREQUEST']._serialized_end=49
  _globals['_STATFIELD']._serialized_start=51
  _globals['_STATFIELD']._serialized_end=91
  _globals['_CATFIELDS']._serialized_start=93
  _globals['_CATFIELDS']._serialized_end=132
  _globals['_STATCATEGORY']._serialized_start=134
  _globals['_STATCATEGORY']._serialized_end=196
  _globals['_PLAYERSTAT']._serialized_start=198
  _globals['_PLAYERSTAT']._serialized_end=261
  _globals['_GETSTATSRESPONSE']._serialized_start=263
  _globals['_GETSTATSRESPONSE']._serialized_end=315
  _globals['_STATS']._serialized_start=317
  _globals['_STATS']._serialized_end=375
# @@protoc_insertion_point(module_scope)
