# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import stats_pb2 as stats__pb2


class statsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getStats = channel.unary_unary(
                '/stats/getStats',
                request_serializer=stats__pb2.GetStatsRequest.SerializeToString,
                response_deserializer=stats__pb2.GetStatsResponse.FromString,
                )


class statsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_statsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getStats': grpc.unary_unary_rpc_method_handler(
                    servicer.getStats,
                    request_deserializer=stats__pb2.GetStatsRequest.FromString,
                    response_serializer=stats__pb2.GetStatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stats', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class stats(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stats/getStats',
            stats__pb2.GetStatsRequest.SerializeToString,
            stats__pb2.GetStatsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
